### ISSUE TITLE
Experiment metadata overview tab content enhancements

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/eRA#10]
The following pieces of information are either not necessary for page display (but must be retained for the machine readable content) or need tweaking:

-Type -> Research Station Field :- remove
- Soil properties table is missing. e.g. see GLTEN metadata for Broadbalk

Also, there needs to be spacing between the final white box on each tab.

**Comment by nathcast** [comment]
> The following pieces of information are either not necessary for page display (but must be retained for the machine readable content) or need tweaking:

Done. What we need to keep in the machine readable json file can be worked out later : so raising an issue for that.

**Comment by nathcast** [comment]
> * Soil properties table is missing. e.g. see GLTEN metadata for Broadbalk

This will be sorted when one of us can run db2json and reconciliate GLTEN and the site.

**Comment by nathcast** [comment]
> Also, there needs to be spacing between the final white box on each tab.

Yes: I have spotted that too: and have tried but so far no joy. I put that as a new issue so that we can close that one. 

Thanks,

**Comment by richardostler** [comment]
I'll close this once I've run db2json and re-checked

**Comment by nathcast** [comment]
I added the soil properties (they were missing indeed) 
TODO in DB to JSON, pull Depth  when it is there and then come back here to add depth to table.

**Comment by richardostler** [comment]
Looks good.
