### ISSUE TITLE
Experiment datasets - works better as accordion display?

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/eRA#11]
Can we try the list of experiment datasets as an accordian display - given there may be multiple datasets listed, the accordian display will compact the list and make it easier to scan.

Alternatively see this [design used by CEH-EIDC](https://catalogue.ceh.ac.uk/documents/4971bce4-8a81-4e23-9637-7fcff37c5f21) 

Also, how is the list ordered? Can it be weighted so that more important / popular datasets are listed first?

**Comment by nathcast** [comment]
> Also, how is the list ordered? Can it be weighted so that more important / popular datasets are listed first?

If we want to weight them, then we need a way to pin some on top. This should be in the database (datacite) So a 0/1 (important or not) or a grading (1-5) to assign specific importance. I think that for the moment, we could code for the later (1-5) but expect a vote 1 or 5 from the curators: your thoughts?

How do you want list ordered? most recent first? alphabetic? 

Already, I would like to be able to filter the latest versions (having a way to find them) ...

**Comment by nathcast** [comment]
Testing the "card display" as in ECN: see tab "Dataset Cards" as we know what the accordions will look like. 
![Annotation 2020-04-23 114720](https://user-images.githubusercontent.com/36696807/80090942-3883cf00-8558-11ea-88d8-cabf37022e9b.png)

**Comment by richardostler** [comment]
I quite like the card layout. I think I prefer to have clickable cards, with the mouse rollover highlighting, similar to the CEH model - I don't think the DOI is necessary here. It would be good to have them all consistently sized, even if that means truncating some of the description text - the dataset titles alone ought to be meaningful enough.

Regards weighting, this is definitely necessary, then sorted alphabetically. We should discuss with Margaret and Sarah what granularity is required.

**Comment by nathcast** [comment]
I have replaced teh DOI in the footer by a button that says More... and made the whole card clickable. 

I have made the cards the same size in their rows. 

To have cards all the same size, it would be best if the descriptions are roughly the same size. That can be acheived by 
1: either in the database, asking curators to only have the same average number of characters (so a bout 300 characters
or 
2: chop the string to 300 characters which I have done. This is very crude and I want to improve it to either finish the sentence so go to next  or previous full stop , whichever is teh closest (but sometimes the "." is not a full stop... So the test would be that the if the word before the full stop is only one letter, then it is not a full stop...

**Comment by nathcast** [comment]
Now made a function which chop the description before 300 (or any number we chose) if the next one brings it above that length, the next sentnce is not added. 
Im happy with that. It would be best that curators keep abtracts desriptions below an aggreed string length.

**Comment by nathcast** [comment]
Also added this design to the weather Data.

**Comment by richardostler** [comment]
Really like the new display format, clear and easy to read. I think we can still 'chop' longer text as it still serves a purpose, so rather than limit the amount of text I think it is better to recommend the first few sentences should have most impact re introducing the dataset.
