### ISSUE TITLE
Refactoring About tab menu items + new pages

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/eRA#12]
Sorry quite a lot here, but seemed sensible to put everything together! I've set it up as a task list so we can check items off as they're done :)

Remove the following menu items:
- [x] Standards -> Pesticides used - this is a very long lists. Pesticide information will be made available as part of the farm management data
- [x] Standards -> Conventions 
- [x] Standards heading

- [x] Create a new tab called 'Data'
- [x] Move About -> Standards -> Data Quality to this tab. I assume this page will use the current E-RA website [data quality page](http://www.era.rothamsted.ac.uk/dataq) as the basis? If so...
- [x] Create draft data quality page using existing content
- [x] Move About -> Standards -> Conversion Factors to this Data tab- I can't find an existing page on the current e-RA site, but we can use the pages from the yield books for content
- [x] Create draft conversion factors page
- [x] Move About -> About -> Access to Data to the new Data tab
- [x] Add direct links for each Experiment's Datasets tab
- [x] Create a new menu-item for 'other datasets' this will be other OA datasets unrelated to either LTEs or Met data, e.g. Soil Fumigation Experiments
- [x] Move About->News and Updates->Data Updates to the new Data tab

- [x] Promote Sites to main tab
- [x] Create place holder pages for each site. Some content can be copied over from the existing site (e.g. http://www.era.rothamsted.ac.uk/WoburnFarm)

**Comment by nathcast** [comment]
> * Promote Sites to main tab

In the main tab, I have already a header that is the name of the stations (sites) : I could just make that a link to the station as it was intented originally
![Annotation 2020-04-23 132521](https://user-images.githubusercontent.com/36696807/80099138-e77ad780-8565-11ea-9e92-8e0f05a13745.png)

**Comment by nathcast** [comment]
> * Add direct links for each Experiment's Datasets tab

I have added link to the experiments that have dasets so far.

**Comment by nathcast** [comment]
> * Create place holder pages for each site. Some content can be copied over from the existing site (e.g. http://www.era.rothamsted.ac.uk/WoburnFarm)

I have created space holder for the information about the sites.

**Comment by nathcast** [comment]
I have finished items on the list: 
However, we need to think about how we feed the weather station pages and the sttion pages. 
Is it easier to feed json files with desciptions or write bits of php pages. 
As the pages have a complicated structure and therefore easible breakable, I feel I need to offer a clear pattern and then the part are filled with php pages that could be either hardcoded or json files. 
At the moment, the woburn page for example, does not work and I don;t know why.

**Comment by nathcast** [comment]
For the Sites: I use a page called farm: 
tabs are fed by either code or hardcoded pages that are easier to maintain for the webmasters/
the page looks for the folder for that farm (rothamsted, broomsbarn ... ) and picks up there the file

- summary.php for the overview tab
- history.php for the history tab
- the images are served by usual tool that looks into a databse
- we could also have a tab for the bibliography

I think the tab summary could be coded using a json string because it would then also make it FAIR. But the history tab can remain as a hard coded tab. 

tab experiments could be harcoded in page experiments.php but then curators will have to get back to it to update (how often do we need to add experiments???) 
or coded using a json list as the experiments are already available in the database: but then, we need some extra fields to separate classicals from LTE and others. So a hardcoded page might be better.

**Comment by nathcast** [comment]
Finally: Made placeholder files for all "farms" 
so for each farm, there will be the following php files which are simple HTML files. 
summary.php
history.php
site.php
experiments.php

We also need a summary.json file to feed the schema information for google.

**Comment by richardostler** [comment]
> > * Create place holder pages for each site. Some content can be copied over from the existing site (e.g. http://www.era.rothamsted.ac.uk/WoburnFarm)
> 
> I have created space holder for the information about the sites.

I can't see this, nor can I see the main menu item for sites?

**Comment by nathcast** [comment]
> I can't see this, nor can I see the main menu item for sites?

I have now added the "SITES" tab menu at the top

**Comment by richardostler** [comment]
@nathcast do you want to keep this open for the summary.json or put as a new issue and close this one?

**Comment by nathcast** [comment]
this issue is about the tab manu item. I would prefer dealing with other issues of contents in other pages. So I will close this one and we will open Content issues to be dealt separatly 
It gives a sense of acchievement to close issues or click boxes. :)
