### ISSUE TITLE
content: conversion factors

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#16]
Please add content to the Converion factor page: 
you will find it in Teams > eRA > web site update > FILES > webPages > default > CF.php

![Annotation 2020-04-23 133936](https://user-images.githubusercontent.com/36696807/80100449-e5197d00-8567-11ea-97f3-0032a3276dd8.png)

I hope the screenshots help.

**Comment by Perrymas** [comment]
Hi Nathalie, I have found this page CF.php. I will discuss with Margaret just what we need to put there. Sarah

**Comment by mglendining** [comment]
Hi Nathalie, could you give some ideas of what you will use this for? Do you want eg Imperial to metric  measurements ((inches to mm, cwt/acre to kg/ha)? Thank you

**Comment by nathcast** [comment]
> Hi Nathalie, could you give some ideas of what you will use this for? Do you want eg Imperial to metric measurements ((inches to mm, cwt/acre to kg/ha)? Thank you

This is the conversion factor page that is used in all the Yields books. So a direct copy of that in HTML format would be great. 

Note: **Do not close the issues**: just press the green button. thanks,

**Comment by mglendining** [comment]
HI Nathalie
Can you give me an idea of the format you would like in the html page?
Are you going to use these conversion factors within e-RA, or is it just text that you want, eg
'Factors for the conversion of Imperial to Metric Units' Heading 2
Then a list, eg
1 inch (in.) = 2.540 centimeters (cm).

Do you just want me to type it in and format it?
Thanks
Margaret
________________________________

**Comment by mglendining** [comment]
Hi Nathalie, I have added a file called Conversion Factors_MJG, it is just in word, so I leave you to format it. It doesn't need to be in tables, but it looks quite neat that way. 
It is in e-RA - Documents\eRA web site update\WebPages\default

**Comment by nathcast** [comment]
I have HTMLised the CF page. 
The reference to the DEFRA booklet at the end has now moved from https://www.gov.uk/government/publications/fertiliser-manual-rb209--2  to https://ahdb.org.uk/rb209 : I have edited the reference accordingliy.

**Comment by mglendining** [comment]
Thanks. I have made some minor corrections to it.
Sarah would you have a chance to look and see what you think?.

M
________________________________

**Comment by Perrymas** [comment]
Yes, sure, I am trying to finish the EdX course today, when my internet allows

sarah

________________________________

**Comment by Perrymas** [comment]
Hi. I have edited the references because there were inconsistent style in dates and apostrophes and order. 
Also, Equation 2, about beaufort scale, in the Word file is not in the HTML file. If it was intentionally removed you can remover the (1) from the list of equations.
Many thanks for doing this.

**Comment by nathcast** [comment]
> Also, Equation 2, about beaufort scale, in the Word file is not in the HTML file. If it was intentionally removed you can remover the (1) from the list of equations.

Oops not meant to remove it. I have put it back now. 
Thanks for editing the references.

**Comment by nathcast** [comment]
There is a note in measurements.html to add this to conversion factors. 
	<p>Vh/V10 = 0.233+0.656*log10 (h+4.75), where Vh = speed in knots
						at height h, V10 = speed at 10m and h = height in m (Met Office
						1982). ADD THIS TO CONVERSTION FACTORS??</p>

- [x] check this when it is done.

**Comment by mglendining** [comment]
This is now done
Margaret

________________________________

**Comment by mglendining** [comment]
Nathalie Can we have a link in the RMS description of wind run to the conversion factors page, to show the calculation used to convert 10 m to 2m? Shown as [link to] in RMS text.
