### ISSUE TITLE
Security Work

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#19]
- [x] Contact IT and ask for their advice 

from IT advice: 
**MEDIUM**

- [x] It is possible to view the directory listing
- [x] The identified library bootstrap, version 4.1.1 is vulnerable.
- [ ] X-Frame-Options Header Not Set > constantin

**LOW**

- [ ] Absence of Anti-CSRF Tokens
- [ ] Cookie No HttpOnly Flag
- [ ] Cookie Without SameSite Attribute
- [ ] Cross-Domain JavaScript Source File Inclusion
- [ ] Server Leaks Information via "X-Powered-By" HTTP Response Header Field(s)
- [ ] X-Content-Type-Options Header Missing

**OTHER**
- [x] Read information from Richard and act upon what's relevant >> move to next year

**Comment by nathcast** [comment]
https://blog.r2c.dev/2020/preventing-sql-injection-a-django-authors-perspective/

**Comment by richardostler** [comment]
https://developers.google.com/recaptcha/docs/v3

**Comment by nathcast** [comment]
Paul’s code is really only there to prevent malicious user input, so it seems redundant to me to check this on every page as most pages won’t expect user input. Therefore it is simply better to strip any unexpected input as it arrives. Of course if you are passing parameters in the code, you should always sanitize before using.
 
I have run a few free test tools and the below HTTP headers come up frequently, so you should investigate these (see below). I think you should also contact ITS to see if they have any penetration testing tools that we can use – they will much better flag-up security issues and how best to mitigate.
 
In the meantime read up on PHP security at https://www.php.net/manual/en/security.php
 
OWASP have some good resources - https://owasp.org/www-project-web-security-testing-guide/stable/4-Web_Application_Security_Testing/07-Input_Validation_Testing/README.html 
 

Another useful site.. https://www.acunetix.com/websitesecurity/php-security-1/, https://www.wordfence.com/learn/how-to-write-secure-php-code/

 
Risk description:
Because the X-Frame-Options header is not sent by the server, an attacker could embed this website into an iframe of a third party website. By manipulating the display attributes of the iframe, the attacker could trick the user into performing mouse clicks in the application, thus performing activities without user's consent (ex: delete user, subscribe to newsletter, etc). This is called a Clickjacking attack and it is described in detail here:
https://www.owasp.org/index.php/Clickjacking

The X-XSS-Protection HTTP header instructs the browser to stop loading web pages when they detect reflected Cross-Site Scripting (XSS) attacks. Lack of this header exposes application users to XSS attacks in case the web application contains such vulnerability.

The HTTP X-Content-Type-Options header is addressed to Internet Explorer browser and prevents it from reinterpreting the content of a web page (MIME-sniffing) and thus overriding the value of the Content-Type header). Lack of this header could lead to attacks such as Cross-Site Scripting or phishing.

Recommendation:
We recommend you to add the X-Frame-Options HTTP response header to every page that you want to be protected against Clickjacking attacks.
More information about this issue:
https://www.owasp.org/index.php/Clickjacking_Defense_Cheat_Sheet

We recommend setting the X-XSS-Protection header to "X-XSS-Protection: 1; mode=block".
More information about this issue:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection

We recommend setting the X-Content-Type-Options header to "X-Content-Type-Options: nosniff".
More information about this issue:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

**Comment by nathcast** [comment]
IT gave me a report: 
http://local-info.rothamsted.ac.uk/eRA/era2018-new/zeRA_Security_Scan2021-04-15.html

a few issues, but nothing serious. I will go through them but they are not a problem. 
N

**Comment by nathcast** [comment]
There are no major points, I have done the Medium ones that I could do. 
THere is  no flag for SQL injection: the user has limited rigts so no real issues there.

**Comment by nathcast** [comment]
A solution to really deal with SQL injection is that I modify the way I do the query to use prepared statements. That could be obj for after launch.
