### ISSUE TITLE
Design Tab

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#2]
I have noticed that the "design Tab" repeated some fields. I have sorted the obvious one: I need to check that what I am returning is what I have in the json file.

**Comment by nathcast** [comment]
Also check the spacings within that tab.

**Comment by nathcast** [comment]
I have sorted out the bug that caused the repeat of "design" and tidied up that tab. 
Data is provided by filling in the GLTEN site and updating the json files using my python tools. 

Please comment on style.

**Comment by richardostler** [comment]
Looks ok so far, but it isn't yet representing the full set of metadata which is available. e.g. Broadbalk has metadata also has crop rotations and factors/factor levels which aren't being displayed by e-RA.

**Comment by nathcast** [comment]
I need to update the json files with new data from GLTEN. I think that I could choose a day / time in the week when I push all the updates to the data - How uptodate do we want that? eventually, I guess a tool can be ran automatically to get the updated information regularly. 
That is an enhancement for db2json

**Comment by nathcast** [comment]
> Looks ok so far, but it isn't yet representing the full set of metadata which is available. e.g. Broadbalk has metadata also has crop rotations and factors/factor levels which aren't being displayed by e-RA.

This will be sorted when db2json can be run. Can we close this issue please?
