### ISSUE TITLE
CSS: Brown background

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/eRA#20]
Sorry, I'm starting to find the brown background very drab! Can we change to white?

**Comment by nathcast** [comment]
![image](https://user-images.githubusercontent.com/36696807/80957360-e6b23300-8dfa-11ea-974f-7c6e33ef6133.png)
I have made the background slightly off white. 
bootstrap4 uses SASS: we write scss files and use a workflow to make css files out of these SCSS files. 
When close to launch, I suppose we will have a review of all the style and then I will rebuilt my SASS workflow. This will ensure all the colors are in teh correct shades accross the site.

**Comment by richardostler** [comment]
I prefer this new background!
