### ISSUE TITLE
content: admin texts

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#21]
- [x] Data Access Policy for overview page (condition of access page)
- [x] updae license for datasets and condition of access
- [x] Boiler Plate Funding for LTE experiments

- [x]  Boiler Plate Funding for DATASETS

In Access Use and Conditions:

- [x] Change the section title to Dataset Access and Conditions
- [x] The citation example has '_Rothamsted Research (N/A)_' remove the N/A
- [x] The 'Conditions of use' link does not work

**Comment by nathcast** [comment]
I have used the text in Data Access and Funding text for new website_MJG_SP.docx to update the expt and dataset pages.

**Comment by richardostler** [comment]
In Access Use and Conditions:

- [x] Change the section title to Dataset Access and Conditions
- [x] The citation example has '_Rothamsted Research (N/A)_' remove the N/A
- [x] The 'Conditions of use' link does not work

**Comment by nathcast** [comment]
I have remove the link to "condition of use" until we have a special paragraph about it. I think the text below is enough, 

The (N/A) is some datasets is because no "date of publication was entered. 
I have replaced this by either the year of creation or the year of publication (4th first characters of the relevant dates) if none of these two are available then I return a blank string, So in the datacite database, we must have at least a date of creation or a date or publication.
