### ISSUE TITLE
Update data access to PDO:: 

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#23]
This is really old code and it's about time I review it to access the database object to PDO:: classes 
For this I will need to read up and then modify the code. 
This concerns the access to the database for the Biblography.

**Comment by richardostler** [comment]
@nathcast is still an issue or has the code been updated?

**Comment by nathcast** [comment]
Hi; I have not updated to PDO, but I am using the mysqli php code which works. So this is not done, but I do not believe is urgent.
