### ISSUE TITLE
_design.php

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#24]
-  [x] Crop Rotations
- [x] Factors
- [x] Factor combinations

**Comment by nathcast** [comment]
On Crop rotations: I want a card design, however, there is a bug and so far no joy. The bottom of my cards is missing a border. so I made the Crop Rotations little lists.

**Comment by nathcast** [comment]
I think I am outputing all that is outputted in the GLTEN. 
An improvement would be to somehow have a on hover tip that comes up when hovering on a factor to link to corresponding one on list above.

**Comment by richardostler** [comment]
Looks good - I'm going to create a new issue for some edits
