### ISSUE TITLE
Links to external sites should ope in a new tab/window

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/eRA#25]
For example, on Rothamsted site pages, 'more' links open pages from rothamsted.ac.uk

There are links to outside of eRA in:

- [x] header
- [x] some hard coded pages.
- [x] pages where people provide ORCIDs
- [x] DOIs

I might want to see if I can get Javascript to do that for me:)

**Comment by nathcast** [comment]
Hi. 
I know that some pages do it and even it is done in eRA, however, even now, the UX community is really divided  around that practice and I would like that we have a look at these. Some compare it to the coke/pepsi war... 
I have read a few articles some for, some against, and this one is a good summary: 

https://www.caktusgroup.com/blog/2017/03/01/opening-external-links-same-tab-or-new/

based on that, I would opt for the "clearly marked external link policy" but would also like to encourage the team to read on that too.

**Comment by richardostler** [comment]
Hi Nath,

I don’t want to turn this into a big discussion point and would prefer the new tab by default for external sites (I’m one of those people who’ll however over a link and click the new tab option!). From the article below I would argue links would generally fall into the ‘reference’ category.

Cheers

Richard

**Comment by nathcast** [comment]
Ok: done.
Sometimes I have put the external link icon when it is necessary

I have done it in I think all the pages that are coded, so that is uniform, 
For the pages that still need to be written, or in the process of being finished, I need to instruct Margaret and Sarah about links and then check.
