### ISSUE TITLE
Grade Datasets

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#26]
The datasets in the Dataset page, need to be graded

- [x] extra field in database, 
- [x] update db2json to reflect extra field 
- [x] update code to sort according to grade and year DESC

**Comment by nathcast** [comment]
The datasets.json file which lists the datasets is ordered by db2json so no need to update the code to sort it... :)

**Comment by nathcast** [comment]
Try broadbalk where i have ordered the datasets: it works 
So pending the grading by M and S

**Comment by richardostler** [comment]
Looks to be working ok to me

**Comment by richardostler** [comment]
@nathcast I thought this was resolved?

**Comment by nathcast** [comment]
Hi: when we when back from the Lockdown database, the grades where lost: please check that they are still ok, or review them. thanks,

**Comment by Perrymas** [comment]
I did that last week, but am unable to open datacite today :-(

**Comment by mglendining** [comment]
Have you managed to open Datacite?

________________________________

**Comment by Perrymas** [comment]
I have - but I don't have the expanded boxes!
