### ISSUE TITLE
content: grade datasets

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#27]
I have added a field in the datacite database to add the grade of the datasets (and documents) 

You will find the LOCKDWN database in 
https://rothamsted.sharepoint.com/:f:/s/e-RA/Ei7EzwsAQsVOnsLmOYSWsV4BaYEw6Dd7rbRSVIlmxZeNdQ?e=uNLfvJ

You can update the grades using the form : frm_metadata_document and you will find the field on teh right. 

![image](https://user-images.githubusercontent.com/36696807/82435439-3a27b080-9a8c-11ea-857c-ca0400d9fcb7.png)

You can also open the TABLE metadata_document
I have put the grade field near the title, and the datasets have a grt_id of 4. 
![image](https://user-images.githubusercontent.com/36696807/82436162-495b2e00-9a8d-11ea-9c19-626e86eb9399.png)

So it is ready for you to add grades to the datasets.

**Comment by mglendining** [comment]
Hi Nathalie
Is 1 low importance and 3 high?
M
________________________________

**Comment by mglendining** [comment]
Sorry, Nathalie, but I can't see it.
I assume it is the lockdown version? The box for 'grade' is not there in the version I just looked at.

Margaret
________________________________

**Comment by nathcast** [comment]
Ok: I am going to sync the versions,,,
and then you can sync too,
sorry: I forgat that bit.

Nathalie Castells-Brooke
Bioinformatics Consultant
Biomathematics and Bioinformatics Division
Rothamsted Research
Harpenden
Al5 2JQ
________________________________

**Comment by mglendining** [comment]
OK, I'll look at it tomorrow now.
I don't work this afternoon.
Thanks
M
________________________________

**Comment by Perrymas** [comment]
ok

________________________________

**Comment by Perrymas** [comment]
I've been trying to do the course, sorry not to get round to this.

sarah

________________________________

**Comment by Perrymas** [comment]
ok, i have found the lockdown database. IT goes into Ellen's user name unfortunately.
I assume I work on it and then upload it back? or syn it back?

sarah

________________________________
