### ISSUE TITLE
Edits for Experiment Design Measurements

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/eRA#29]
Looking at Broadbalk period 1 there are a couple of display issues - not sure if this is a GLTEN API problem or not.

- [x] Some variable names are 'Default title'
- [x] Crops are showing with a number rather than name
- [x] Material values are under the 'scale' heading and not showing correctly
- [x] Not sure what 'scale' is - can you remove? I think it might be a redundant field.
- [x] Can you reduce the font size to fit the table better?

**Comment by nathcast** [comment]
The Default title: problem in GLTN when there is no variable name

**Comment by nathcast** [comment]
all done
