### ISSUE TITLE
_dataset.php : Click Through Licensing

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#30]
Provide a way to have a click through licence so a verbal agreement that people know that there is a licence before they proceed to the link. 

- [x] - click through with agree and download for OA datasets
- [x] make zip files
- [x] start cokkies
- [x] start sessions
- [x] cookie banner to accept cookies
- [x] make function to differentiate OA to big ones

- [x] database table to handle registerd users
- [x] registration form
- [x] no password link confirmation system to login 
- [x] handled via a pop up
- [x] returns to last viewed dataset

**Comment by nathcast** [comment]
First trial: I have made a modal that is showed at clicking of the download button: I am on the right track? 

Here is the idea that people would only be given the choice to download the whole data package as a zip file. The list of files above the download button will just give info on what files there are and the download will get them all, including the datapackage that is provided. 
Or we couls also that that same behavior from the link tha will bring out the modal for the individual file. Do we want people to download files individually?

Please comment.

**Comment by richardostler** [comment]
Zip file so they have everything together

**Comment by nathcast** [comment]
Updating the header to that issue to baby step this .

**Comment by nathcast** [comment]
https://code.tutsplus.com/tutorials/how-to-code-a-signup-form-with-email-confirmation--net-6860

https://www.123-reg.co.uk/blog/email-marketing/beginners-guide-to-building-your-first-email-list/

**Comment by nathcast** [comment]
I had more thought about click trough licencing and what it means for a user to be "registered". I am thinking of using cookies and sessions, and a simple for that ask for email address or twitter handle. If it is an email address, it is easy to verify that they have sent their own email address. If the point of the click through is to remind people to quote our OA datasets in their papers, then from time to time we send an email or a link to the form or a survey to remind them to tell us about their work. No need to have a database of users of the OA: I can plant a cookie. So I am thinking along these lines. So we will be in effect maintaining a distribution list for people who want to use OAs and a database for people who want to use the other datasets. It will be possible to block access to users that do not have the right cookie. Of course I also need to make one of these HUGE banners to warn users about them and so on. Not trivial but we should get there. Smiley

**Comment by nathcast** [comment]
There is now a quick form to enter an email address. 
At the moment, the email address is entered as a cookie 
If the cookie is there, the email address is shown and we can use that to do masses of thins/ 

I have also prepared a table to add the email address to the database: there will need to be a verification code . 
So an email address needs to be registered and verified to work. 
Verifying and email address is just sending an email that has a link to action the function that will compare the code with the cookie registered in the email... we will work that out. 

When we have a database, we can start playing.. 

Next we want the download button to be here for non OA stuff only if the user is logged in

**Comment by nathcast** [comment]
Demonstrated at last meeting

**Comment by nathcast** [comment]
HI; I have I think finised this and would like it tested by you guys to iron out little things, 
Plese let me know (here???) what you think, thanks,

**Comment by nathcast** [comment]
What I want to do now is return to same window in the browser .. So need the page to name the window / tab (using jquery) and then make the link that target that page.. 
This will prevent opeining other pages.

**Comment by nathcast** [comment]
I can rename the window, but a link from email to a named window does not load the link in that window. So we have to work with another window being opened. At least the window keeps the history.
