### ISSUE TITLE
content: registration forms

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#33]
The forms for the registration are all in the group eRA-requests 

https://forms.office.com/Pages/DesignPage.aspx?origin=OfficeDotCom&lang=en-US#

To get to them, go to microsoft office forms and choose group forms. If you don;t see these forms straight away there should be a way to find teh group eRA request. 
When you click on a form that way, it is easy to edit. 

I have made a video: 

https://rothamsted.sharepoint.com/:v:/s/e-RA/EU46xJuDT9NDmJ6oAFR9_zABDIQRL8K3LhqHqdamkwvP1g?e=4grQey

Four forms 
registrations for UN and PW: met, data external and data internal. 
quick form for a quick akonwlegement of why use of data. 

Thanks

**Comment by nathcast** [comment]
See email trail about it and https://rothamsted.sharepoint.com/:x:/r/sites/e-RA/_layouts/15/Doc.aspx?sourcedoc=%7B95D113DA-F5BF-44E0-9FC9-4C5D4A93A9C4%7D&file=Revised%20questions%20for%20data%20requests.xlsx&wdLOR=cFEE9EFE3-97CA-4BB5-A27E-79FC7FF1D80A&action=default&mobileredirect=true#
) 
(file in general/website development

**Comment by nathcast** [comment]
Hi: we are not working anymore with these 4 forms: so I would like to clode that and start an ew issue to track the work I do on the new registration form.

**Comment by mglendining** [comment]
OK, I'm happy with that.
M

________________________________

**Comment by richardostler** [comment]
OK, I'll close this one then

**Comment by mglendining** [comment]
I have made comments on this in the file.
M

________________________________

**Comment by Perrymas** [comment]
I tried seeing that and could not….
