### ISSUE TITLE
content: DOI to the BUCKS paper

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#38]
The DOI to the BUCKS paper is not working. 
It needs investigating

**Comment by mglendining** [comment]
I contacted the Journal, who replied very quickly. They have a problem with old journals, and are looking to resolve this problem, but don't have a date for that. In the meantime, I suggest we delete the link, just leave the reference and add to TODO list.

**Comment by nathcast** [comment]
Decided to leave the links in place as the journal are going to sort it out. It is not our issue.

**Comment by mglendining** [comment]
I'm happy with that.
