### ISSUE TITLE
Rothamsted weather datasets part of Brooms Barn LSRE

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/eRA#40]
The Rothamsted weather datasets are being shown as part of the Brooms Barn LSRE on the dataset pages.

**Comment by nathcast** [comment]
Sorry: I am not sure what you are talking about: please explain.

**Comment by nathcast** [comment]
I htkn I have sorted it out, however, I am not sure what you are refering to: if you still see that, please explain better 
It is best if you quote the URL you are displayed and what you are looking at. thanks,

**Comment by richardostler** [comment]
Can o longer replicate as pages have been updated, therefore assume closed
