### ISSUE TITLE
No Page for Conditions of Use

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/eRA#41]
This Conditions of Use page is missing

**Comment by nathcast** [comment]
Please quote the URL of the page you are viewing when making a comment. I do know knw what this is about. Thanks

**Comment by richardostler** [comment]
Hi Nath, I'm a bit confused about this issue - can we just ignore and remove?

**Comment by richardostler** [comment]
I've added this page with content.
