### ISSUE TITLE
Measuring Weather/Derived variables page

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/eRA#42]
- [x] The link title (in the nav menu) and page title should be the same - I'm not sure if the page is only meant to list derived variables so unsure on the best title.
- [x] There is a rogue punctuation immediately after the title
- [x] All of the hyperlinked variable names that I tested are broken

**Comment by nathcast** [comment]
> [ ] There is a rogue punctuation immediately after the title

I cannot see that: it might be a bug due to the server side scripting.. so lets ignore these for the moment. 


> * The link title (in the nav menu) and page title should be the same - I'm not sure if the page is only meant to list derived variables so unsure on the best title.

This is a menu issue: will correct it all at once at the end.
