### ISSUE TITLE
content: rms - Rothamsted Met station page

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/eRA#43]
- [x] Rogue punctuation symbols before the title on the Measurements tab
- [x] Also on the measurements tab there is a rogue 'F' before the table
- [x] Remove the Data Access and License sections from the overview page

**These are the pages that are needed** 

- [x] summary.html - introduction and overview
- [x] equipment.html - about the machines
- [x] measurements.html about the measurements (probably done)
- [x] monthly.html - monthly summary if available 
- [x] extreme.html - Extreme weather events at Rothamsted
- [x] 30yearmean.html - 30-year weather means at Rothamsted - the page on the old site is from october 2019 
- [x] soils.html - information about the site, soil type
- [x] history.html : History of recording weather at Rothamsted

**Comment by nathcast** [comment]
> * Rogue punctuation symbols before the title on the Measurements tab

Sorry: can't see it..

**Comment by mglendining** [comment]
I have made some small updates to the rms measurements page.

**Comment by mglendining** [comment]
@Nathalie I have added some more pages in the list above. These need creating.

**Comment by nathcast** [comment]
I have added the fllowing pages: :extreme, 30yearmean and history, 
I think History is good to go, but please checj. 

I want to do a bit more on extreme to clean up the formating and on 30yearsmean to add the images. So I will let you know when these are ready.

**Comment by mglendining** [comment]
Hi @nathcast I think History is OK. It could always have more added to it, but will do for now.

**Comment by mglendining** [comment]
@nathcast can you add a page for rms for the soils? This describes the soil at the met station, we already have it and I don't think it needs much extra work. Thanks

**Comment by mglendining** [comment]
@nathcast we still have a page in rms called 'background' but that is no longer required, as all the information is in summary. Thanks.

**Comment by mglendining** [comment]
History is good to go, it just needs your comments at the top of the page removing.
M
________________________________

**Comment by nathcast** [comment]
I have made a lot of corrections to the 4 met stations pages: 
Will you look at rms/extreme.html 
and also in met: the school pages 
We also need images for bms, wms and sms

**Comment by mglendining** [comment]
Hi Nath
I'm not quite sure what you want doing with the Schools and Extremes pages.  Sarah has put these together, so probably better to ask her than me (not wishing to pass the buck...).
THanks
Margaret

________________________________

**Comment by Perrymas** [comment]
Yes sure, I have those both on my list to do 😊

**Comment by richardostler** [comment]
@Perrymas to update Extremes then can be closed
