### ISSUE TITLE
content: wms - Woburn Met Station

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/eRA#44]
- [x] The overview and Site page both have the same content - looks like there is a bug which means content isn't being correctly separated between the two tabs
- [x] Remove Data Access and License sections from overview page
- [x] On the Measurements tab, there is a rogue 'S' before the table and the table is hyperlinked to the Request Data Access page

**These are the pages that are needed** 
_check when done or if irrelevant_

- [x] summary.html - introduction and overview
- [x] equipment.html - about the machines
- [x] measurements.html about the measurements
- [ ] monthly.html - monthly summary if available 
- [x] Check that the datasets associated with wms are in the datacite db (when we can access it) and that the actual datasets are in the repository - make a note of what is missing

- [ ] wms- line 254 - CLOUD <b>[NEED TO FIND OUT WHEN THIS STOPPED Appears in WOBMET header file 1962.]</b>

- [x] wms- line 304 <p>From 1999 WINDSP has been calculated as an average over 10 minutes from 8.50 to 9am **[CHECK WITH TONY]**.

- [ ] Check if Relativel Humidity was measured at wms 1928-70 by checking photocopied monthly data sheets (in cupboard in printer room).

**Comment by Perrymas** [comment]
I edited 'took over' to 'commenced'; added missing variables to list of those measured; added my orcid id; changed 'In progress, remove when' to 'Ready to'. Then moved from 'in progress' to 'done' column.

**Comment by Perrymas** [comment]
In measurements, I edited some typos (minimum instead of mimimum, mercury instead of mecury; also some commas and fullstops missing were added in. Also, rejigged some sentences for consistency; chnaged column titles - Dates recorded instead of when recorded; Measurement methods instead of Methods of ...

**Comment by mglendining** [comment]
Thanks Sarah, all sounds good.

________________________________

**Comment by mglendining** [comment]
@richardostler @nathcast I have updated all the Met. Office data used in the measurements file (c) Crown Copyright relevant year.
