### ISSUE TITLE
content: sms - saxmundham met station

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/eRA#45]
**These are the pages that are needed** 
_please check when done or irrelevant_ 

- [x] summary.html - introduction and overview

- [x] measurements.html about the measurements

- [x] Check that the datasets associated with sms are in the datacite db (when we can access it) and that the actual datasets are in the repository

**Comment by nathcast** [comment]
If we replace the present way of serving "station.php" information with actual web pages for overviews and so on, then I believe this issue will go away.

**Comment by mglendining** [comment]
I have completed the summary page for Saxmundham

**Comment by mglendining** [comment]
I have completed the measurements page for sms. @nathcast  please can you check that the link to the Open Access DOI which contains the data, is correct. This is the monthly summary, so I assume we don't also need a separate page for monthly summaries? The data is not availalbe from the DET, but as an existing DOI. 
@Perrymas please can you read and check, and also the summary page. It should then all be done.

**Comment by Perrymas** [comment]
Hi. I have read and tweeked both the summary and measurements pages. All good to go now.
Can the open access link be instucted to open in a new webpage? 
Although, the other links to Sample Archive etc don't open in a new page either. Is this the policy through-out the entire website? It is personal preference I guess - I prefer new pages to open and not to lose the original webpage, but maybe oterhs prefer a new page to over-rule the previous page?

**Comment by mglendining** [comment]
Hi Sarah,
thanks for checking that.
I'm with you, I prefer a link to open in a new webpage, but I don't know how to set that up.
Nathalie, can you advise?
Thanks
Margaret
________________________________

**Comment by nathcast** [comment]
The DOI here is a link to one of our own DOI (a dataset) 

We could discuss where links open: I think that links to our own DOI (which will stay on the site) should stay in the page unless we have a good reason to send them to another page: like here? so links to anything like href="www.era.rothamsted.ac.uk/" or to non full URLS that are relative to us (or DOIS that would land on our pages should stay on same page. S
Other links could go to other target="_blank" pages but that has not been checked yet. 
Your thoughts?

**Comment by nathcast** [comment]
Made the datasets a separate issue .
