### ISSUE TITLE
content: bms - brooms barn met station

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#46]
**These are the pages that are needed** 
_Please check when done or if irrelevant_

- [x] summary.html - introduction and overview

- [x] measurements.html about the measurements

- [x] Check that the datasets associated with bms are n the datacite db (when we can access it) and that the actual datasets are in the repository

- [x] bms. We used Met Office data for 5 variables Aug 2009 - May 2012. We have shown this a (c) Crown Copyright Met Office in the website. How to show this, so it can be used. @richardostler .

**Comment by mglendining** [comment]
@nathcast I think all the  'equipment' at the met stations is covered in the measurements page, so this is not required, unless you want to extract it from the measurements pages.

**Comment by nathcast** [comment]
I removed equipment tab

**Comment by mglendining** [comment]
I have finished the measurement and summary pages. @Perrymas please can you check you are happy with it.

**Comment by Perrymas** [comment]
I have checked and slightly tweeked the summary and Measuremetns pages. Good to go.

**Comment by nathcast** [comment]
I have checked the summary page, the measurement pages, removed the curating tag, and added targets to the external links. 
I have also update teh associated json file so that the correct descriptions are added to the header: title, meta, and json string for SEO. 

@richardostler : I do not remember what we said about licence for met experiment: this is for the json string.  

The GOogle search engine now uses Rich Test Results https://search.google.com/test/rich-results?utm_campaign=sdtt&utm_medium=message to test the json and as it is , the station pages are not eligible.

**Comment by nathcast** [comment]
I ahve made the dataset comment a separate issue  (dataset : bms)

**Comment by mglendining** [comment]
@richardostler @nathcast I have added (c) Crown Copyright (year) published by the Met. Office after every variable that used Met Office data, as checked by Tony.
