### ISSUE TITLE
content: met pages

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#47]
these are pages that are common to all the met data: They are in the **met** folder

- [x] derived_variables,html
- [ ] schools.html
- [ ] public.html

**Comment by nathcast** [comment]
I have split the schools pages into public which is more general and probably should have the bulk of the explanations, and schools which will have the links to the worksheets. 

There are a lot of spreadsheets associated with the public and school pages. 
: are they alreaday datasets with DOIS? or do they need DOIs? 

The pdfs of the worksheets need updating with the new LOGOs. 

These three datasets in DET public, schoolmetday and schoolmetmth need to have entries in the datacite database so that they have a DOI and then they will be listed in the datasets list. Information about them as well as the associated PDFs for school work could be entered in the database instead of maintainaing a web page.

**Comment by mglendining** [comment]
@nathcast I have checked derived variables and added an introductory sentence and title. This is good to go, you just need to remove the comments at the start of the page Nathalie.

**Comment by richardostler** [comment]
Not sure what the status of this is - I can still see red comments on a few sections e.g. http://local-info.rothamsted.ac.uk/eRA/era2018-new/station/rms/extreme#documents plus Schools, public and Equipment pages. Schools and Public pages both look more than good enough, but Equipment is still empty

**Comment by richardostler** [comment]
Removed Equipment from this issue - create a new one for 2022 (Tony to help). @nathcast to tidy up schools and publics then close

**Comment by Perrymas** [comment]
I  have worked on schools and public pages today. Added Excel files to folder as links were not working and editing broken links. I have made comments at tops of files - edits required for Nathalie. Also, query why the Public page is title 'schools' and yet in file it says Public...?
