### ISSUE TITLE
Link to a specific tab in the experiment page

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#5]
I want to be able to point a link to a specific tab in the tab design of a page. I know it just needs a bit of jQuery at the rightplace. and I think I found out which one it is. I just dont knwo where the code goes: I have never done jQuery. 

Thanks for that.

**Comment by nathcast** [comment]
Thanks Alberto for guidanec in that. That is nw working.

**Comment by nathcast** [comment]
There is still a problem with that: sometimes, the link clicked goes straight to the desired tab, and sometimes, the page needs a page refreshed to go to it. 
Also, I never get tto see the actual tabIndex styled as it should be.

**Comment by stellalberto** [comment]
We can have another look on Tuesday, is it ok?

**Comment by richardostler** [comment]
Sorry @nathcast not sure what input you need from me here?
