### ISSUE TITLE
datasets: bms

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#50]
Upload all the bms datasets to the web site

for xls (OA) dataset: 
load the files in the repository
enter information in datacite, (DET datasets have type HTML
run db2json tool
synchronise the files

Before we launch we want at least one dataset then this will be part of maintenance workflow

**Comment by richardostler** [comment]
No summary datasets yet - may consider this for later

**Comment by Perrymas** [comment]
I checked the text - ok, except can the link to ECN open in a new page 'target blank' please.
I found a photo of Brooms barn met station to  add as there are currently no images - saved it in images>brooms barn.
Otherwise, ready to go as a basic weather site entry.

**Comment by nathcast** [comment]
This is a content issue so does not belong in GITHUB. It can be closed and archived. Thanks
