### ISSUE TITLE
Bibliography workflow

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#55]
We have a problem with importing references in the database. this will affect the new site but also affect the old site. The new version of mysql, or XL are chocking on the standart used. I have managed to import a full complement of the references on 16th sept,  but have not manages to reproduce that. . 

- [ ] Make a doc for the settings in Endnote

**Comment by nathcast** [comment]
Open bibliography in endnote. If not woking properly, check stettings
Use eRA Tab Delimited export filter
Import the text file in exel
Check the records - Especally ensure that there are no rogue lines that denote a carriage return in any of the records

save as csv (comma delimited) 

in dbeaver, 
import csv, using windows-1252 

For the next few times I will do it until I have clear documentation

**Comment by richardostler** [comment]
Hi @nathcast, I'm not clear if this is ready to be closed. Has this been tested further and the documentation available?

**Comment by nathcast** [comment]
It works> I have also made a CheatSheet documentation file that resides in the bibliography folder. I
