### ISSUE TITLE
_bottom.Tidy up the page footer

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/eRA#57]
Can you tidy up the page footer.

- [x] reduce the size of the Rothamsted and BBSRC logos - similar size to the Rothamsted site should be fine
- [x] I don't think we need all the text, please can you remove all except for the sentence about contacting the e-RA team
- [x] Can you reduce the font size for the the sentence about contacting e-RA, change the font to dark and background to white and remove the button - its redundant as we have the mailto link already in the text.
- [x] check the display - on some pages its full width on others it isn't

**Comment by richardostler** [comment]
Some of the text ("You can browse....") is also duplicated on the homepage, appearing both in the body and footer of the page.

**Comment by nathcast** [comment]
Regarding the display: when it is full width, it means that there is a div too many in the file above: so that needs to be corrected in the relevant pages.

**Comment by nathcast** [comment]
The bottom is quite short now. I hope we have no pages that will be too short.

**Comment by richardostler** [comment]
Looks much better :)
