### ISSUE TITLE
_dataset.php: reorganise what is in accordion and not

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#59]
Regarding what is in the dataset page: 
**at the moment we have first, under a simple h3**

- abstract
- methods,
- table of contents.
- ... 

under accordion: 

- related identidiers
- funding
- licence and data access

**It is suggested to change it so that we have** 

At the top under h3 headings (for which the size will be revisited in Issue 58)
- Abstract
- Related Identifiers
- Data access and licences

then under accordions

- Methods
- table of contents.
- ... and all the other different fields that we could have.

ToDO: 

- [x] Confirm the above plan with the team
- [x] implement the plan

**Comment by nathcast** [comment]
I have made accordions where needed . Please comment

**Comment by richardostler** [comment]
I think this looks OK - closing
