### ISSUE TITLE
includes/user: registration - email to curators on confirmation

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#63]
At the moment, the email to curators is sent at the same time as the confirmation email to the user. 
It would be nice to only send email to curators when the email address is confirmed. 

That will be more important when the email is sent about Request. 
At the moment, we could just not removed the curators from the list of email sent.

**Comment by richardostler** [comment]
Lets leave as it is for now and we can monitor to see if this is a problem and revisit then
