### ISSUE TITLE
orphans.php: page for orphan datasets

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#65]
We have datasets that are not related to a LTE. 

- [x] orphan.php lists the orphan datasets
- [x] When viewing an orphan dataset, the expt need to come back to expt=rro
- [x] If expt = rro: use the orphan.php page. 
 
a dataset in rro expt do not have expt: so put an iff in the _dataset page.

**Comment by nathcast** [comment]
http://local-info.rothamsted.ac.uk/eRA/era2018-new/orphans.php : this is the page that list the orphan datasets: the ones that have no LTE associated with them: 
PLease check that you like it especially the text: 
`These datasets have been produced by the eRA team out of data from an experiment that has not yet got a Long-tterm experiment status`

**Comment by nathcast** [comment]
call it OTHER

**Comment by mglendining** [comment]
Hi @nathcast thanks for changing to 'other' I would prefer the text below to read 
Datasets produced from other field experiments at Rothamsted (not long-term experiments) 
Thank you

**Comment by Perrymas** [comment]
Yes, I agree, or perhaps 'Datasets derived from other field experiments at Rothamsted (not Classical or long-term experiments)'

**Comment by mglendining** [comment]
Happy with that.
