### ISSUE TITLE
_contact.php: update contacts

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#67]
Use the green site page to update the _people page

**Comment by nathcast** [comment]
I have made the page http://local-info.rothamsted.ac.uk/eRA/era2018-new/info/credits to contain the past and present staff in one place. I have used the original credit's page from the old site .I have reformated using a more logical type and will eventually add margin. 
I have added Claudia and Vera which were missing. 

Please review, and add years when known, and people that have beed omitted. This is a start... N

**Comment by mglendining** [comment]
Dear Nathalie
Sorry, but I have no idea what this means! It says I don't have any public repositories yet.
Thanks
Margaret

________________________________

**Comment by mglendining** [comment]
Claudia Underwood and I started working on e-RA in Dec 2008, when Gill Tuck left.

**Comment by mglendining** [comment]
Note spelling of Vera Wiltsher
