### ISSUE TITLE
expt.php: videos

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#68]
Initial query: Do we want to embed or do we want to link?

Now obsolete> we move the Videos to the Media tab and just have a link. 
I guess later, we could have also a thumbnail? But at the moment a link is enough!

**Comment by richardostler** [comment]
I can see current set-up is to link out to a new tab. I think this is fine for now but we can revisit after the site is released. Moving to 2022 project.

**Comment by nathcast** [comment]
- [x] rename images tab to "media"  and list in that tab presentations and videos too.
