### ISSUE TITLE
_dataset.php: detailed contributor information

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#70]
ON the right side of the dataset page, have a table to list contributors and how they contributed. Use regex tpo math camelcase with a space.

**Comment by nathcast** [comment]
code could includetry  this: $str = preg_replace('/([a-z])([A-Z])/', "\\1 \\2", "DataCurator"); 

it is; 
```

 $strRole = preg_replace('/([a-z])([A-Z])/', '${1} ${2}', $contributor['jobTitle']);
                $strRole = strtolower($strRole);
                $strRole = ucfirst($strRole);
```

The info we have on a contributor is: 



```
  | {
  | "type": "Person",
  | "Name": "Andrew Macdonald",
  | "givenName": "Andrew",
  | "familyName": "Macdonald",
  | "sameAs": "https://orcid.org/0000-0002-1785-4892",
  | "address": {
  | "type": "PostalAddress",
  | "streetAddress": "Sustainable Agricultural Sciences, Rothamsted Research",
  | "addressLocality": "Harpenden",
  | "addressRegion": "Hertfordshire",
  | "postalCode": "AL5 2JQ",
  | "addressCountry": "United Kingdom"
  | },
  | "affiliation": {
  | "type": "Organization",
  | "name": "Sustainable Agricultural Sciences, Rothamsted Research",
  | "address": ", West Common, Harpenden, Hertfordshire, AL5 2JQ, United Kingdom"
  | }
  | },


```

so I could include a link to the ORCID page or sort by familyName for example. I made it a list; it could be a table. I could sort by roles.

**Comment by Perrymas** [comment]
As we have discussed before 'the roles' attributed to the contributors are very restrictive e.g. Wendy, Melanies etc are listed as Data Collectors. I am not sure they would like that as a named role.
Including the Orchid id may help this as the link can be followed to get precise detail on their roles.
In your first comment above, when you say on 'the right hand side' do you actually mean the left hand side? Or are you suggesting to make another list on the RHS?

**Comment by Perrymas** [comment]
Hi Nathalie, I have seen what you have done now - listing the roles of the contributors on the 'RHS'/main body of the web page of the datasets - looks good :) @nathcast

**Comment by nathcast** [comment]
Some contributors will not have ORCID IDs. The roles here are restricted by the schema.

**Comment by Perrymas** [comment]
Yes, sure,  it will be good to include the Credit's page from current website is so useful - to have a general overview of peoples roles. I will update that with some extra information Wendy Gregory has just sent.

**Comment by mglendining** [comment]
@Perrymas is it worth asking Wendy what they would like to be described as, if you think 'data collector' is not what they want? We could call them 'researcher', though I don't think they think of themselves as that. Any other ideas from the list of possibles?

**Comment by mglendining** [comment]
Sorry, I know I am not supposed to close this. Not sure how else to send the message.

**Comment by nathcast** [comment]
> @Perrymas is it worth asking Wendy what they would like to be described as, if you think 'data collector' is not what they want? We could call them 'researcher', though I don't think they think of themselves as that. Any other ideas from the list of possibles?

These are the only two that would apply to them. If we want something else, it would fall out of the Schema. You can be a bit more precise in the package? you can describe in the spreadsheet with more details. 

(save the comment by clicking the big green button)

**Comment by Perrymas** [comment]
I think we mentioned ' researcher' as an option in the meeting we had with Wendy, but she did not think that was appropriate (nor 'technician'). If we list the techniques they do on the credits page - which I will add soon - that will be useful. Chris Hall and Andy etc are also described as collectors in some datasets. Maybe Wendy and team are actually 'Data Creators' ?

**Comment by mglendining** [comment]
@Perrymas do you want to check with Wendy what she is happy with Sarah? Give her the options available in Datacite.

**Comment by Perrymas** [comment]
ok, when i send her the updated credits page I will explain our predicament and clarify what she's prefer :-)
