### ISSUE TITLE
_dataset: date published 

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#72]
Remove publication date, and tidy up the problme with the dates: 
The minting tool must only add DOI_created the first time, and as teh DOI_created is added, then add a record in document-date: data available
Then (if DOI_created) add record to document-dates : dateUpdated (so curator don;t have to manage that. 
The publication date is Date Created. 
then it is all teh updated dates, and we list only the last update

- [ ] remove publication date (which is never used)
- [ ] update minting too with what is above
- [ ] update PHP with the proper listing of Publication Date as Date Created (the first one) and then updated.

**Comment by richardostler** [comment]
Decided at team meeting to rename creation date to publication date. Once this has been done move issue to 2022 project
