### ISSUE TITLE
Geescroft Wilderness - Datasets tab but no datasets

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/eRA#73]
Gesscroft Wilderness Experiment pages has a Datasets tab but no datasets are listed.

What we want is: 

- [x] no dataset or all datasets have isREADY == 0 >>> no display in 2021 or 2018
- [ ] if all the datsets in the list are isReady == 1 then display tab in 2018 but not in 2021
- [ ] if at least one dataset has "isReady == 2" then display in 2021 and 2018

**Comment by nathcast** [comment]
Hi. 
The "datasets.json" file in there was a legacy. At the moment there are no dataset that are ready to even check so I have removed that. Now the tab is not showing. (I used to display all the datasets: now only showing datasets that have a 1 or above.

**Comment by nathcast** [comment]
I have also amended the condition for displaying the dataset tab in the 2021 version to (has at least one dataset that is isReady == 2 so that I won;t have an emtpy tab if all the datasets in the list are isReady == 1... :) 
so I think that is ready but I have not checked that this function works.
