### ISSUE TITLE
content: menus

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#74]
List here menu items that need to be added and need to be removed or comments

- [x] make the info.php  NICELINK:

**Comment by mglendining** [comment]
Can we have a bit more detail here please? I'm not sure what this means. Thanks

**Comment by Perrymas** [comment]
What page does this refer to?

**Comment by nathcast** [comment]
This is refereeing to the header drop down menu.




Sent from my Galaxy



-------- Original message --------
From: Perrymas ***@***.***>
Date: 05/05/2021 15:51 (GMT+00:00)
To: Rothamsted-Ecoinformatics/eRA ***@***.***>
Cc: Nathalie Castells ***@***.***>, Assign ***@***.***>
Subject: Re: [Rothamsted-Ecoinformatics/eRA] content: menus (#74)


CAUTION: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.


What page does this refer to?

**Comment by mglendining** [comment]
Dear Nathalie
I'm still not sure what I am supposed to be doing with this. Thanks
M

________________________________
