### ISSUE TITLE
_dataset: providing support for external datasets

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#78]
The possibility to add external datasets that have been created using samples or data from LTEs. 
Our first external dataset is the ANdy neal study: rrn1/METAGEN in the repo and the datacite database and the link is at: 
http://local-info.rothamsted.ac.uk/eRA/era2018-new/dataset/rrn1/01-METAGEN 

Issues to look at: 
It  is preferable that the same entry system is used to enter externals as internals however, we cannot mint DOIs from these.

- [x] add isExternal field to metadatadocument
- [x] ensure isExternal are not minted: modify code in database.py and mintall.py
- [x] Modify the db2json to add the isExternal marker in the datasets.json and the datasetname.jsons files
- [x] For the web page: modify the page so that the external dataset listing is presenting less data

**Comment by nathcast** [comment]
I have done the back-end for this feature. 
Now, I am going to continue the front end work and modify the dataset page so that the external dataset shows only what is needed. I have made a start. I have added the rest of the team for feedback and comments as I do that.

**Comment by nathcast** [comment]
Design options: 
I had the options to either design a brand new style for the external datasets, or put ifs and elses in the one we have now. I have chosen the second option.

**Comment by mglendining** [comment]
OK, thanks. I can't see it anywhere, will you send us a link when you need comments.


________________________________

**Comment by nathcast** [comment]
An example of external dataset is at http://local-info.rothamsted.ac.uk/eRA/era2018-new/dataset/rrn1/01-METAGEN
It is the dataset in rrn1 / METAGEN in teh repository and datacite db

**Comment by nathcast** [comment]
I have updated the datacite interface for this new feature> please ensure you pick up the latest version. :)

**Comment by nathcast** [comment]
I have corrected the code the shows or not contributors and dates/ There is no data for date so the dates do not show. WHen dates are added to the list, the the page should pick it up. Please add at least one date to see if that works/

**Comment by mglendining** [comment]
Hi
I have set the date as 'available'. Is that OK?
M

________________________________

**Comment by richardostler** [comment]
@nathcast, @mglendining is this resolved? I can see dates for the metagenomic dataset on era-2018?

**Comment by mglendining** [comment]
This isn't yet completed. Still waiting to hear back from Andy Neal. I'll chase him.
M

________________________________
