### ISSUE TITLE
Preserve GLTEN paragraph formatting

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/eRA#8]
Paragraph formatting is being lost e.g. see the experiment design description for Broadbalk current period is [one paragraph block](http://local-info.rothamsted.ac.uk/eRA/era2018-new/expt.php?expt=rbk1), whereas [GLTEN](https://www.glten.org/experiments/1) is several paragraph blocks.

Assuming the formatting isn't lost in the JSON extracted from GLTEN, please can you preserve it.

**Comment by nathcast** [comment]
I have added   style=\"white-space: pre-wrap;\" to the tag that styles the descriptions in (I beleive) al the fields that are susceptble to have a long description. Now, the carriage returns will be visible. 

If that is enough, please close issue. Or raise a "new feature request" to make a function to enable a better treatment of text fields. (when data input allows for MD)

**Comment by richardostler** [comment]
Seems to be working well, so should be fine for now.
