### ISSUE TITLE
registerGold: add field "where heard from"

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#80]
Add a "How did you hear about this " field to questionairee

- [x] to dabase
- [x] field in PHP
- [x] check the variable is passed and is persistent accross the pages of the form
- [x] write to email
- [x] write to database

**Comment by nathcast** [comment]
from Sarah
Regarding the question for people registering that we briefly discussed this morning:- 

The list we currently have in our Access Database of Users is;

•	Contact
•	Newsletter
•	Poster
•	Web
•	Other (specify)

Do you all think we could also add;

•	Twitter
•	LinkedIn
•	Staff
•	Previous user

Any changes/other options?

Sarah
Notes from emails. 
I don't think we need poster or newsletter as a category, I have never used those. 
As Comms said they would put our new era website in the next Rothamsted Research newsletter it may be relevant, but again it could go under ‘other specify’, that was also why I mentioned LinkedIn, but that could go under ‘other specify’ too.

**Comment by nathcast** [comment]
Please check on the 2018 interface . Thanks,

**Comment by richardostler** [comment]
I'm happy with this, closing
