### ISSUE TITLE
_dataset page: "Dataset: " in the title

### ISSUE THREAD

**Issue by nathcast** [Rothamsted-Ecoinformatics/eRA#83]
My code for the web site adds “Dataset: “ in front of the title of the datasets. It did not include it in the reference. So there is a discrepancy.
to solve that, some have started to name the Datasets: "Dataset: title "  in the database but that resulted 
in the page titled showing “Dataset: Dataset: TITLE of Dataset”

To remedy that I have coded the following: 
For a Dataset: if the title (in the database) includes Dataset, then the title of the page will remain unchanged. If the title does not include dataset, then the title will be changed to be “Dataset: Title of the Dataset”. This title is then used in the header on the page for the dataset, and also in the “how to reference the dataset part. 

I probably need to change that in the minting tool, to reflect that and then mint all the datasets that will then have a changed name. 
Let’s chat about that at the next Catch up. 

Nath
It is always the issue: do I make changes to what is displayed: in the Data  , in how it is exported in the json files and minted  , or in the web page?

**Comment by Perrymas** [comment]
Thanks Nathalie. Thanks for adapting this to the new datasets I have created, to accommodate the fact I out 'Dataset' in the title. Just how to apply this to previous datasets already named we can discuss. cheers
