### ISSUE TITLE
Experiment metadata overview tab content enhancements

### ISSUE THREAD

**Issue by richardostler** [Rothamsted-Ecoinformatics/eRA#9]
The following pieces of information are either not necessary for page display (but must be retained for the machine readable content) or need tweaking:

- [x] - General Information -> Type: Experiment (they're all experiments!) - remove
- [x] - General Information -> Title: - remove, this is already given above the tabs
- [x] - Timeline -> Temporal Coverage: remove this - it simply restates Date Start and Date End
- [x] - Data Access -> I think the current headings you have here need to go and a generic piece of text adding in place. I'll draft this as a separate issue and circulate with Margaret and Sarah too.
- [x] - Licence -> strictly this should be the licence for the metadata which is CC0, but again I think we also need some generic text for this.
- [x] - Contributors -> reformat so that the name is included in the white box. Additional information i.e. role (data manager), contact details should also be included. We should check with M&S that the associated people are correct.
- [x] - Need a new section for funding. This should be in GLTEN, but we could equally add this as boiler plate to all experiments.
- [ ]

**Comment by nathcast** [comment]
> * Contributors -> reformat so that the name is included in the white box.
 Done

**Comment by nathcast** [comment]
> * Additional information i.e. role (data manager), contact details should also be included. We should check with M&S that the associated people are correct.
I have added the Role. 

In the index page , I have linked the team's details with their page at Rothamsted. On this page fed by the database (datacite database) we could also have a link to the rothamsted page, or people who provide their ORCID can feed ORCID with their contact information. 
This info comes from GLTEN. Is there a field in GLTEN toprovide link to persons profiles pages on ROthamsted? or do I need to do something to capture that with PHP?

**Comment by nathcast** [comment]
> * We should check with M&S that the associated people are correct. 
Experiment data is fed in GLTEN so if that is correct then that will be reflected here

**Comment by nathcast** [comment]
> * Need a new section for funding. This should be in GLTEN, but we could equally add this as boiler plate to all experiments.

At the moment we have funding info in datacite for indivisual dataasets/documents. not experiments. 
Experiment info is taken from GLTEN: shall we wait till funding info can be extracted from GLTEN? or make necessary changes to datacite db to add funding info to experiments (which would mean entering same info twice)

**Comment by nathcast** [comment]
> * Timeline -> Temporal Coverage: remove this - it simply restates Date Start and Date End

done

**Comment by nathcast** [comment]
> * General Information -> Type: Experiment (they're all experiments!) - remove
> * General Information -> Title: - remove, this is already given above the tabs
> * Timeline -> Temporal Coverage: remove this - it simply restates Date Start and Date End

Done

**Comment by nathcast** [comment]
> * Data Access -> I think the current headings you have here need to go and a generic piece of text adding in place. I'll draft this as a separate issue and circulate with Margaret and Sarah too.

The fields available for DataAccess in the schema are: 
 ```
 dataAccess= dict(
        type= "creativeWork",
        conditionsOfAccess= data['data_statement_label'],
        isAccessibleForFree= data['data_policy_status'],
        publishingPrinciples= data['data_url'],
        actionableFeedbackPolicy= data['objective'],
        correctionsPolicy= data['objective'],
        unnamedSourcesPolicy= data['data_policy_url']
    ),

```
as seen here, some are linked to dummy data (data[objective] because that data is not in GLTEN yet. If we have a single document that has the whole policy, then there is a field in GLTEN for that. So the document URL needs to be entered in GLTEN (and hosted on era obvisouly) Summaries for the other items in the schema could be used or I could comment them off (in db2json) 

For this part of the code: I used a function that picks up all the fields in that part. If we only want to display some of them and have more control, then this can be hardcoded in the site.

**Comment by nathcast** [comment]
> * Licence -> strictly this should be the licence for the metadata which is CC0, but again I think we also need some generic text for this.

This is actually hardcoded in db2json: so let me know what is actually needed an I change it in db2json
    license= dict(
        type= "CreativeWork",
        name= "CC-by-4",
        license= "http://creativecommons.org/licenses/by/4.0"
    ),

**Comment by richardostler** [comment]
> On this page fed by the database (datacite database) we could also have a link to the rothamsted page, or people who provide their ORCID can feed ORCID with their contact information.

> This info comes from GLTEN. Is there a field in GLTEN toprovide link to persons profiles pages on ROthamsted? or do I need to do something to capture that with PHP?

GLTEN does have an option to include a website for a person, so we could get them to provide the URL profile page, but this could be difficult to manage if the Rothamted URLs change, so perhaps not that safe to use, so lets just link to their ORCID if provided.

**Comment by richardostler** [comment]
> > * Need a new section for funding. This should be in GLTEN, but we could equally add this as boiler plate to all experiments.
> 
> At the moment we have funding info in datacite for indivisual dataasets/documents. not experiments.
> Experiment info is taken from GLTEN: shall we wait till funding info can be extracted from GLTEN? or make necessary changes to datacite db to add funding info to experiments (which would mean entering same info twice)

I've checked GLTEN and it only allows you to specify the funder role, we also want to specify the grant number(s) so this should either be boiler plate or added to the database for the additional detail, depending on whether some LTEs have additional/alternate funding sources.

**Comment by richardostler** [comment]
> > * Data Access -> I think the current headings you have here need to go and a generic piece of text adding in place. I'll draft this as a separate issue and circulate with Margaret and Sarah too.
> 
> The fields available for DataAccess in the schema are:
> 
> ```
> dataAccess= dict(
>        type= "creativeWork",
>        conditionsOfAccess= data['data_statement_label'],
>        isAccessibleForFree= data['data_policy_status'],
>        publishingPrinciples= data['data_url'],
>        actionableFeedbackPolicy= data['objective'],
>        correctionsPolicy= data['objective'],
>        unnamedSourcesPolicy= data['data_policy_url']
>    ),
> ```
> 
> as seen here, some are linked to dummy data (data[objective] because that data is not in GLTEN yet. If we have a single document that has the whole policy, then there is a field in GLTEN for that. So the document URL needs to be entered in GLTEN (and hosted on era obvisouly) Summaries for the other items in the schema could be used or I could comment them off (in db2json)
> 
> For this part of the code: I used a function that picks up all the fields in that part. If we only want to display some of them and have more control, then this can be hardcoded in the site.

I think we can hard code this as it will be the same for all experiments. For now the relevant part to use will be conditionsOfAccess and creativeWork. We may add in other parts at a later date.

**Comment by nathcast** [comment]
> I think we can hard code this as it will be the same for all experiments. For now the relevant part to use will be conditionsOfAccess and creativeWork. We may add in other parts at a later date.
DataAccess: I commented out what came from the database and prepared placeholder for text from you. and started a separate issue for all the admin official texts that we need. 



Corrected the license in teh code for db2json , and hardcoded the license on the site. Put the logo and a link to the license. Added to separate issue for admin documents

Fundings: same as above: prepared Boiler plate space on page for generic text. and add issue in db2json to extract funding information for experiments in datacite db

**Comment by nathcast** [comment]
I have made the top bit as a check list and AFAIK, i ticked all the boxes I coudl do regarding _summary.php and opened separate issues for what needs to be done elsewhere. Can we close this? thanks

https://github.com/Rothamsted-Ecoinformatics/eRA/issues/21#issue-612460107

https://github.com/Rothamsted-Ecoinformatics/db2json/issues/5#issue-612477962
